Robot connect
LiU-SeeGoals/basestation pull request #11
Opened 2024-04-10 18:27 UTC by Paladinking

Working robot communication, pinging + synchronization using tx_semaphore.

2024-04-15 17:21 UTC, r0x57n commented on .mxproject
> +SourceFiles=Core\Src\main.c;Core\Src\tx_initialize_low_level.S;NetXDuo\App\app_netxduo.c;Core\Src\app_threadx.c;AZURE_RTOS\App\app_azure_rtos.c;Core\Src\stm32h5xx_it.c;Core\Src\stm32h5xx_hal_msp.c;Co
ouggggh

2024-04-15 17:24 UTC, r0x57n commented on AZURE_RTOS/App/app_azure_rtos_config.h
> +#define TX_APP_MEM_POOL_SIZE                     4096
visst behövdes detta i slutändan, inte bara nånting vi glömde kvar?

2024-04-15 17:29 UTC, r0x57n requested changes
Kolla kommentarer, men utöver dom så kan jag inte bygga:
/home/re/dev/seegoals/basestation/Core/Src/com.c:5:10: fatal error: nrf_helper_defines.h: No such file or directory
    5 | #include <nrf_helper_defines.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/basestation.elf.dir/build.make:104: CMakeFiles/basestation.elf.dir/Core/Src/com.c.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/re/dev/seegoals/basestation/Core/Src/handle_packet.c:3:10: fatal error: robot_action/robot_action.pb-c.h: No such file or directory
    3 | #include <robot_action/robot_action.pb-c.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

2024-04-15 17:44 UTC, Paladinking commented on AZURE_RTOS/App/app_azure_rtos_config.h
> +#define TX_APP_MEM_POOL_SIZE                     4096
Ja, det behövs, 1024 var för lite.

2024-04-15 18:53 UTC, Paladinking commented
> Kolla kommentarer, men utöver dom så kan jag inte bygga: /home/re/dev/seegoals/basestation/Core/Src/com.c:5:10: fatal error: nrf_helper_defines.h: No such file or directory 5 | #include <nrf_helper_defines.h> | ^~~~~~~~~~~~~~~~~~~~~~ compilation terminated. make[2]: *** [CMakeFiles/basestation.elf.dir/build.make:104: CMakeFiles/basestation.elf.dir/Core/Src/com.c.obj] Error 1 make[2]: *** Waiting for unfinished jobs.... /home/re/dev/seegoals/basestation/Core/Src/handle_packet.c:3:10: fatal error: robot_action/robot_action.pb-c.h: No such file or directory 3 | #include <robot_action/robot_action.pb-c.h> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated.

Jag lyckas inte upprepa detta, gjorde en build på en dator som inte hade något installerat och det fungerade.
Var dina submoduler updaterade rätt @r0x57n ?

2024-04-17 16:40 UTC, r0x57n approved these changes

2024-04-17 16:53 UTC, merged